services:
  training-pos-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  training-pos-cache:
    image: redis
    ports:
      - 6379:6379
