const MIDDLEWARE_ERROR_NOTOKEN = "No token specified";
const MIDDLEWARE_ERROR_TOKENINVALID = "Token invalid";
const MIDDLEWARE_ERROR_CACHEINVALID = "Cache invalid";
const MIDDLEWARE_ERROR_NOPERMISSION = "No Permission";

module.exports = {
  MIDDLEWARE_ERROR_NOTOKEN,
  MIDDLEWARE_ERROR_TOKENINVALID,
  MIDDLEWARE_ERROR_CACHEINVALID,
  MIDDLEWARE_ERROR_NOPERMISSION,
}